### Sentiment Analysis on a reviews.txt file using Bidirectional LSTM RNN

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('reviews.txt' , sep='\t' , names=['Reviews' , 'Comments'])

In [3]:
df.head()

Reviews                                           Comments
0        1            The Da Vinci Code book is just awesome.
1        1  this was the first clive cussler i've ever rea...
2        1                   i liked the Da Vinci Code a lot.
3        1                   i liked the Da Vinci Code a lot.
4        1  I liked the Da Vinci Code but it ultimatly did...

In [4]:
df.isnull().sum()

Reviews     0
Comments    0
dtype: int64

In [5]:
df.shape

(6918, 2)

In [6]:
# getting the independent feature
X = df.drop('Reviews' , axis=1)

In [7]:
# getting the dependent features
y = df['Reviews']

In [8]:
# Checking whether the dataset is balanced or not
y.value_counts()

1    3943
0    2975
Name: Reviews, dtype: int64

In [9]:
import tensorflow as tf
tf.__version__

'2.3.1'

In [10]:
# Importing the Important Libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [11]:
# Fixing the vocabulary size
voc_size = 5000

In [12]:
messages = X.copy()

In [13]:
messages

Comments
0               The Da Vinci Code book is just awesome.
1     this was the first clive cussler i've ever rea...
2                      i liked the Da Vinci Code a lot.
3                      i liked the Da Vinci Code a lot.
4     I liked the Da Vinci Code but it ultimatly did...
...                                                 ...
6913                     Brokeback Mountain was boring.
6914       So Brokeback Mountain was really depressing.
6915  As I sit here, watching the MTV Movie Awards, ...
6916    Ok brokeback mountain is such a horrible movie.
6917   Oh, and Brokeback Mountain was a terrible movie.

[6918 rows x 1 columns]

In [14]:
import nltk
import re
from nltk.corpus import stopwords

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Paras
[nltk_data]     Rana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
# Now Implementing the Data Preprocessing using the Porter stemmer technique
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['Comments'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075


3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730


5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
5405
5406
5407
5408
5409


6867
6868
6869
6870
6871
6872
6873
6874
6875
6876
6877
6878
6879
6880
6881
6882
6883
6884
6885
6886
6887
6888
6889
6890
6891
6892
6893
6894
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6905
6906
6907
6908
6909
6910
6911
6912
6913
6914
6915
6916
6917


In [17]:
corpus

['da vinci code book awesom',
 'first clive cussler ever read even book like relic da vinci code plausibl',
 'like da vinci code lot',
 'like da vinci code lot',
 'like da vinci code ultimatli seem hold',
 'even exagger midnight went wal mart buy da vinci code amaz cours',
 'love da vinci code want someth better differ',
 'thought da vinci code great kite runner',
 'da vinci code actual good movi',
 'thought da vinci code pretti good book',
 'da vinci code one beauti movi ive ever seen',
 'da vinci code amaz book get wrong',
 'turn light radio enjoy da vinci code',
 'da vinci code realli good',
 'love da vinci code',
 'love da vinci code',
 'night da vinci code beauti mind',
 'da vinci code awesom book',
 'thing enjoy da vinci code',
 'da vinci code slash amaz race',
 'hey love da vinci code',
 'also love da vinci code',
 'realli enjoy da vinci code thought would disappoint book',
 'like angel demon da vinci code',
 'da vinci code realli good movi',
 'yeah da vinci code awesom movi lik

In [18]:
# One hot encoding of the Corpus that we just got
onehot_repr = [one_hot(words , voc_size) for words in corpus]
print(onehot_repr)

[[3965, 1283, 3707, 1311, 4712], [3994, 2361, 3264, 2345, 2901, 3056, 1311, 43, 1452, 3965, 1283, 3707, 2286], [43, 3965, 1283, 3707, 3682], [43, 3965, 1283, 3707, 3682], [43, 3965, 1283, 3707, 2960, 278, 477], [3056, 4146, 3305, 3030, 3761, 4488, 3563, 3965, 1283, 3707, 610, 4560], [2305, 3965, 1283, 3707, 3563, 3883, 4631, 2456], [4952, 3965, 1283, 3707, 2814, 2259, 84], [3965, 1283, 3707, 2877, 3554, 4792], [4952, 3965, 1283, 3707, 2140, 3554, 1311], [3965, 1283, 3707, 2917, 2619, 4792, 1153, 2345, 2358], [3965, 1283, 3707, 610, 1311, 3047, 3248], [1970, 1676, 4830, 3468, 3965, 1283, 3707], [3965, 1283, 3707, 760, 3554], [2305, 3965, 1283, 3707], [2305, 3965, 1283, 3707], [632, 3965, 1283, 3707, 2619, 1639], [3965, 1283, 3707, 4712, 1311], [12, 3468, 3965, 1283, 3707], [3965, 1283, 3707, 569, 610, 1307], [1010, 2305, 3965, 1283, 3707], [2887, 2305, 3965, 1283, 3707], [760, 3468, 3965, 1283, 3707, 4952, 124, 2000, 1311], [43, 4569, 4028, 3965, 1283, 3707], [3965, 1283, 3707, 760, 355

### Embedding Representation

In [19]:
sent_length = 30
embedded_docs = pad_sequences(onehot_repr , padding='pre' , maxlen=sent_length)
embedded_docs

array([[   0,    0,    0, ..., 3707, 1311, 4712],
       [   0,    0,    0, ..., 1283, 3707, 2286],
       [   0,    0,    0, ..., 1283, 3707, 3682],
       ...,
       [   0,    0,    0, ..., 4792, 3418, 4504],
       [   0,    0,    0, ..., 4504, 2666, 4792],
       [   0,    0,    0, ..., 4504, 1021, 4792]])

In [20]:
# Creating the model...
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.optimizers import Adam

# Define the parameters
embedding_vector_features = 60
voc_size = 5000  # Example vocabulary size, change as needed
sent_length = 30  # Example sentence length, change as needed

# Create the model
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=embedding_vector_features, input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Print the model summary
model.build(input_shape=(None, sent_length))  # Manually build the model with the input shape
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 30, 60)            300000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               128800    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 429,001
Trainable params: 429,001
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
# Converting the embedded docs to a numpy array
X_final = np.array(embedded_docs)
y_final = np.array(y)

### Train-Test Split

In [22]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X_final , y_final , test_size=0.33 , random_state=42)

In [23]:
# Training the Model....
model.fit(X_train , y_train , validation_data=(X_test , y_test) , epochs=10 , batch_size=32)

Epoch 1/10
145/145 [==============================] - 5s 37ms/step - loss: 0.2727 - accuracy: 0.8762 - val_loss: 0.0790 - val_accuracy: 0.9728
Epoch 2/10
145/145 [==============================] - 5s 35ms/step - loss: 0.0314 - accuracy: 0.9892 - val_loss: 0.0520 - val_accuracy: 0.9847
Epoch 3/10
145/145 [==============================] - 5s 33ms/step - loss: 0.0095 - accuracy: 0.9972 - val_loss: 0.0739 - val_accuracy: 0.9781
Epoch 4/10
145/145 [==============================] - 5s 34ms/step - loss: 0.0048 - accuracy: 0.9985 - val_loss: 0.0449 - val_accuracy: 0.9864
Epoch 5/10
145/145 [==============================] - 5s 35ms/step - loss: 0.0021 - accuracy: 0.9991 - val_loss: 0.0544 - val_accuracy: 0.9855
Epoch 6/10
145/145 [==============================] - 5s 33ms/step - loss: 7.4991e-04 - accuracy: 1.0000 - val_loss: 0.0564 - val_accuracy: 0.9869
Epoch 7/10
145/145 [==============================] - 5s 32ms/step - loss: 3.1494e-04 - accuracy: 1.0000 - val_loss: 0.0615 - val_accuracy

In [24]:
y_pred = model.predict(X_test)

In [25]:
y_pred

array([[9.9998909e-01],
       [9.9999976e-01],
       [1.0000000e+00],
       ...,
       [5.1642837e-06],
       [9.9996561e-01],
       [9.9988890e-01]], dtype=float32)

In [26]:
import numpy as np
y_pred = np.where(y_pred>=0.5 , 1 , 0)

In [27]:
from sklearn.metrics import confusion_matrix , accuracy_score
confusion_matrix(y_test , y_pred)

array([[ 949,   22],
       [   8, 1304]], dtype=int64)

In [28]:
print(accuracy_score(y_test , y_pred))

0.9868593955321945


In [29]:
import pickle

In [30]:
# Specify the filename with .h5 extension
filename = "nlp_model1.h5"

# Save the model using the Keras save method as pickle is used to store non-tensorflow models
model.save(filename)
